import { useMemo, useState } from 'react';
import { formatGiB, safeAvailable, type StorageAccount } from '@photosync/core';

type NavItem={label:string,icon:string};
const nav:NavItem[]=[{label:'Tổng quan',icon:'⌂'},{label:'Ảnh',icon:'▣'},{label:'Thư viện',icon:'◫'},{label:'Album',icon:'▤'},{label:'Chia sẻ',icon:'↗'},{label:'Địa điểm',icon:'⌖'},{label:'Mọi người',icon:'◉'},{label:'Thư mục',icon:'□'},{label:'Tài khoản lưu trữ',icon:'◈'},{label:'Cài đặt',icon:'⚙'}];
const photos=Array.from({length:24},(_,i)=>`https://picsum.photos/seed/photosync-desktop-${i+1}/900/700`);
const accounts:StorageAccount[]=[
{id:'1',email:'khanh@gmail.com',appUsedBytes:8.2*1024**3,providerFreeBytes:6.8*1024**3},
{id:'2',email:'khanh.work@gmail.com',appUsedBytes:4.1*1024**3,providerFreeBytes:10.9*1024**3},
{id:'3',email:'backup.family@gmail.com',appUsedBytes:2.7*1024**3,providerFreeBytes:12.3*1024**3},
];

export function App(){
 const[active,setActive]=useState('Ảnh'); const[query,setQuery]=useState(''); const[selected,setSelected]=useState<string|null>(null); const[showStorage,setShowStorage]=useState(true); const[showBackup,setShowBackup]=useState(false);
 const totalUsed=useMemo(()=>accounts.reduce((s,a)=>s+a.appUsedBytes,0),[]);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">P</div><div><b>PhotoSync</b><small>Drive Photo Cloud</small></div></div><nav>{nav.map(item=><button key={item.label} className={active===item.label?'nav-item active':'nav-item'} onClick={()=>setActive(item.label)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-status"><span className="status-dot"/><div><b>Đồng bộ đang chạy</b><small>{accounts.length} tài khoản Google Drive</small></div></div></aside>
  <main className="workspace"><header className="topbar"><div><h1>{active}</h1><p>Quản lý và sao lưu ảnh trên mọi thiết bị</p></div><div className="top-actions"><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm ảnh, người, địa điểm..."/><kbd>⌘ K</kbd></div><button className="icon-btn">?</button><button className="avatar">KT</button></div></header>
  <section className="toolbar"><div className="tabs"><button className="selected">Tất cả</button><button>Năm</button><button>Tháng</button><button>Ngày</button><button>Thư mục</button></div><div className="view-actions"><button>⌕</button><button>▦</button><button>⋯</button></div></section>
  <section className="content-area"><div className="gallery-pane"><div className="date-heading"><div><h3>Tháng 5 2024</h3><span>{photos.length} mục</span></div><button>Chọn</button></div><div className="photo-grid">{photos.map((src,i)=><button className="photo-card" key={src} onClick={()=>setSelected(src)}><img src={src} alt={`Photo ${i+1}`}/><span className="photo-check">✓</span></button>)}</div></div>
  <aside className="right-rail"><div className="panel storage-panel"><div className="panel-head"><div><h3>Tài khoản lưu trữ</h3><p>Google Drive pool</p></div><button onClick={()=>setShowStorage(v=>!v)}>⌃</button></div>{showStorage&&<><div className="account-list">{accounts.map(a=>{const used=a.appUsedBytes/1024**3;return <div className="account" key={a.id}><div className="google">G</div><div className="account-info"><div><b>{a.email}</b><span>{used.toFixed(1)} / 10 GB</span></div><div className="progress"><i style={{width:`${Math.min(used/10*100,100)}%`}}/></div><small>Có thể dùng an toàn: {formatGiB(safeAvailable(a))}</small></div></div>})}</div><button className="add-account">＋ Thêm tài khoản Google</button><div className="storage-summary"><div><span>Tổng PhotoSync đã dùng</span><b>{formatGiB(totalUsed)} <small>/ {accounts.length*10} GB</small></b></div><div className="multi-progress"><i style={{width:`${Math.min(totalUsed/(accounts.length*10*1024**3)*100,100)}%`}}/></div><small>Mỗi tài khoản luôn chừa tối thiểu 5 GB</small></div></>}</div>
  <div className="panel backup-panel"><div className="panel-head"><div><h3>Sao lưu</h3><p>Tự động & an toàn</p></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div><button className="backup-option" onClick={()=>setShowBackup(v=>!v)}><div><b>Ảnh & Video</b><small>Chất lượng gốc</small></div><span>›</span></button>{showBackup&&<div className="backup-detail"><label><input type="checkbox" defaultChecked/> Ảnh</label><label><input type="checkbox" defaultChecked/> Video</label><label><input type="checkbox" defaultChecked/> Live Photos</label></div>}<label className="check-row"><input type="checkbox" defaultChecked/> Chỉ dùng Wi‑Fi</label><label className="check-row"><input type="checkbox" defaultChecked/> Chạy khi khởi động máy</label></div>
  <div className="panel activity-panel"><div className="panel-head"><div><h3>Hoạt động gần đây</h3><p>Đồng bộ trực tiếp</p></div><span className="live-dot"/></div>{[0,1,2].map(i=><div className="activity" key={i}><img src={photos[i]} alt="thumb"/><div><b>IMG_20240512_{String(i+1).padStart(4,'0')}.jpg</b><small>Đã tải lên • {i+2} phút trước</small></div><span>✓</span></div>)}<button className="sync-now" onClick={()=>alert('Đã đưa tác vụ đồng bộ vào hàng đợi')}>Chạy đồng bộ ngay</button></div></aside></section></main>
  {selected&&<div className="viewer" onClick={()=>setSelected(null)}><div className="viewer-top"><button>‹</button><div><b>Đà Lạt, Việt Nam</b><small>12 tháng 5, 2024 • 06:45</small></div><span/><button>⋯</button></div><img src={selected} alt="Selected"/><div className="viewer-actions"><button>↗<small>Chia sẻ</small></button><button>♡<small>Yêu thích</small></button><button>◒<small>Chỉnh sửa</small></button><button>⌫<small>Xóa</small></button></div></div>}
 </div>
}
